name: Link checker

on:
  workflow_dispatch:
  schedule:
    - cron: "0 0 * * *"

jobs:
  link-checker:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Link checker
        id: lychee
        uses: lycheeverse/lychee-action@v2
        with:
          args: >-
            --exclude-all-private
            --verbose --no-progress
            --user-agent 'Mozilla/5.0 (Windows NT 10.0; Win64; x64)
            AppleWebKit/537.36 (KHTML, like Gecko) Chrome/116.0.0.0 Safari/537.36'
            --max-redirects 10
            --header "accept=*/*"
            --accept 200,204,206,403,429
            --base 'https://thewiki.moe'
            --exclude-path './docs/hidden'
            --exclude '^https://www.amd.com'
            --exclude '^https://exhentai.org'
            --exclude '^https://www.nzbking.com'
            --exclude '^https://chan.sankakucomplex.com'
            --exclude 'https://discordapp.com/api/guilds/974468300304171038/widget.png?style=banner2'
            --exclude '^https:\/\/.*\.onion$'
            './**/*.md'

        # Notes:
        # - Public trackers, streaming sites, Crunchyroll, Kodi, qBittorrent, etc. return 403
        # - Nyaa returns 429
        # - ./docs/hidden has unmaintained legacy files
        # - AMD fails for unknown reasons, ExHentai is private, and NZBKing has poor uptime

      - name: Create issue from file
        if: env.lychee_exit_code != 0
        uses: peter-evans/create-issue-from-file@v5
        with:
          title: Link Checker Report
          content-filepath: ./lychee/out.md
          labels: report, automated issue
