name: mpv

permissions:
  contents: write

on:
  push:
    paths:
      - "docs/static/tutorials/mpv/portable_config/**/*.*"
      - "docs/tutorials/mpv.md"
      - ".github/workflows/mpv.yml"
  schedule:
    - cron: "0 0 * * *"
  workflow_dispatch:

jobs:
  mpv:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          sparse-checkout: |
            docs/static/tutorials/mpv/portable_config
          fetch-depth: 1

      - name: Download mpv
        uses: robinraju/release-downloader@v1
        with:
          repository: zhongfly/mpv-winbuild
          latest: true
          fileName: "mpv-x86_64-20*-git-*.7z"

      - name: Prepare and extract mpv
        id: mpv-extract
        run: |
          archive=$(ls mpv-*.7z)
          base=$(basename "$archive" .7z)
          commit=$(echo "$archive" | grep -oP '(?<=git-)[0-9a-fA-F]+')
          7z x "$archive" -o"$base"
          cp -r docs/static/tutorials/mpv/portable_config "$base/portable_config"
          echo "fullname=$archive" >> $GITHUB_OUTPUT
          echo "basename=$base" >> $GITHUB_OUTPUT
          echo "commit=$commit" >> $GITHUB_OUTPUT

      - name: Recompress mpv and config
        run: |
          7z a "${{ steps.mpv-extract.outputs.fullname }}" "${{ steps.mpv-extract.outputs.basename }}" -m0=lzma2 -mx9 -mmt=on -md=512m -ms=on
          7z a portable_config.7z docs/static/tutorials/mpv/portable_config -mx3

      - name: Create release
        uses: ncipollo/release-action@v1
        with:
          name: mpv
          tag: mpv
          makeLatest: true
          allowUpdates: true
          replacesArtifacts: true
          artifacts: ${{ steps.mpv-extract.outputs.fullname }}, portable_config.7z
          body: |
            Pre-configured portable MPV based on [zhongfly's build](https://github.com/zhongfly/mpv-winbuild) using 
            the [config](https://github.com/${{ github.repository }}/tree/master/docs/static/tutorials/mpv/portable_config) 
            from [thewiki](https://thewiki.moe/tutorials/mpv/)

            This release is updated daily using [this workflow](https://github.com/${{ github.repository }}/blob/master/.github/workflows/mpv.yml)

            Based on: mpv-player/mpv@${{ steps.mpv-extract.outputs.commit }}

            Logs: https://github.com/${{ github.repository }}/actions/runs/${{ github.run_id }}
