name: Publish

on:
  workflow_dispatch:
  push:

jobs:
  publish:
    name: Publish
    runs-on: ubuntu-latest

    permissions:
      contents: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: 9.x

      - name: Build with Retype
        uses: retypeapp/action-build@v1

      - name: Deploy to GitHub Pages
        uses: retypeapp/action-github-pages@v3
        with:
          update-branch: true
